from enum import Enum


class ConversationState(str, Enum):

    START = "START"

    WAITING_FOR_STATE = "WAITING_FOR_STATE"

    WAITING_FOR_DISTRICT = "WAITING_FOR_DISTRICT"

    WAITING_FOR_CARD_TYPE = "WAITING_FOR_CARD_TYPE"

    WAITING_FOR_DOCUMENTS = "WAITING_FOR_DOCUMENTS"

    READY_TO_SUBMIT = "READY_TO_SUBMIT"

    COMPLETED = "COMPLETED"

    CANCELLED = "CANCELLED"